require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeadsController do

  # This should return the minimal set of attributes required to create a valid
  # Lead. As you add validations to Lead, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leads as @leads" do
      lead = Lead.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leads).should eq([lead])
    end
  end

  describe "GET show" do
    it "assigns the requested lead as @lead" do
      lead = Lead.create! valid_attributes
      get :show, {:id => lead.to_param}, valid_session
      assigns(:lead).should eq(lead)
    end
  end

  describe "GET new" do
    it "assigns a new lead as @lead" do
      get :new, {}, valid_session
      assigns(:lead).should be_a_new(Lead)
    end
  end

  describe "GET edit" do
    it "assigns the requested lead as @lead" do
      lead = Lead.create! valid_attributes
      get :edit, {:id => lead.to_param}, valid_session
      assigns(:lead).should eq(lead)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lead" do
        expect {
          post :create, {:lead => valid_attributes}, valid_session
        }.to change(Lead, :count).by(1)
      end

      it "assigns a newly created lead as @lead" do
        post :create, {:lead => valid_attributes}, valid_session
        assigns(:lead).should be_a(Lead)
        assigns(:lead).should be_persisted
      end

      it "redirects to the created lead" do
        post :create, {:lead => valid_attributes}, valid_session
        response.should redirect_to(Lead.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lead as @lead" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lead.any_instance.stub(:save).and_return(false)
        post :create, {:lead => {}}, valid_session
        assigns(:lead).should be_a_new(Lead)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lead.any_instance.stub(:save).and_return(false)
        post :create, {:lead => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lead" do
        lead = Lead.create! valid_attributes
        # Assuming there are no other leads in the database, this
        # specifies that the Lead created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lead.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lead.to_param, :lead => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lead as @lead" do
        lead = Lead.create! valid_attributes
        put :update, {:id => lead.to_param, :lead => valid_attributes}, valid_session
        assigns(:lead).should eq(lead)
      end

      it "redirects to the lead" do
        lead = Lead.create! valid_attributes
        put :update, {:id => lead.to_param, :lead => valid_attributes}, valid_session
        response.should redirect_to(lead)
      end
    end

    describe "with invalid params" do
      it "assigns the lead as @lead" do
        lead = Lead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lead.any_instance.stub(:save).and_return(false)
        put :update, {:id => lead.to_param, :lead => {}}, valid_session
        assigns(:lead).should eq(lead)
      end

      it "re-renders the 'edit' template" do
        lead = Lead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lead.any_instance.stub(:save).and_return(false)
        put :update, {:id => lead.to_param, :lead => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lead" do
      lead = Lead.create! valid_attributes
      expect {
        delete :destroy, {:id => lead.to_param}, valid_session
      }.to change(Lead, :count).by(-1)
    end

    it "redirects to the leads list" do
      lead = Lead.create! valid_attributes
      delete :destroy, {:id => lead.to_param}, valid_session
      response.should redirect_to(leads_url)
    end
  end

end
